### https://github.com/marketplace/actions/open-journals-pdf-generator
### https://joss.readthedocs.io/en/latest/submitting.html
### Build JOSS paper
### .github/workflows/draft-pdf.yml
### https://github.com/ad-m/github-push-action/issues/44

# name: Paper Draft

name: paper_draft

on:
  push:
    branches:
      - joss

jobs:
  render:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    # checkout source code
    - uses: actions/checkout@master
      with:
        branch: joss
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # ref: ${{ github.event.pull_request.head.joss }}
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-pandoc@v2
    - uses: r-lib/actions/setup-tinytex@v2
    # install rmarkdown
    - name: Install rmarkdown
      run: |
        Rscript -e 'install.packages("rmarkdown")'
    # copy files
    - name: Render Markdown
      run: |
        Rscript -e 'rmarkdown::render("./paper/paper.md")'
    # upload new documentation
    - name: publish to github
      run: |
        git config --local core.autocrlf false
        git config --local user.email "${{ github.actor }}@users.noreply.github.com"
        git config --local user.name "${{ github.actor }}"
        git add . && git add --renormalize .
        git pull origin ${{ github.head_ref }} --autostash --rebase -X ours
        git commit --allow-empty -am "AUTO-GH ACTION: ${{ github.workflow }}"
        NO_PAGER=1 git --no-pager diff HEAD^
        git push origin
    - name: Push changes
      uses: ad-m/github-push-action@master
      # uses: r-lib/github-push-action@master
      with:
        branch: joss
        # persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        # fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
        github_token: ${{ secrets.GITHUB_TOKEN }}
  # paper:
  #   runs-on: ubuntu-latest
  #   env:
  #     GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  #   name: Paper Draft
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v3
  #   - name: Build draft PDF
  #     uses: openjournals/openjournals-draft-action@master
  #     # "paper-path:" i should be the path to the paper within your repo.
  #     with:
  #       journal: joss
  #       paper-path: paper/paper.md
  #   - name: Upload
  #     uses: actions/upload-artifact@v1
  #     # "path:" is the output path where Pandoc will write the compiled
  #     # PDF. Note, this should be the same directory as the input
  #     # paper.md
  #     with:
  #       branch: joss
  #       github_token: ${{ secrets.GITHUB_TOKEN }}
  #       name: paper
  #       path: paper/paper.pdf
