name: joss_dev

on:
  push:
    branches:
      - joss

jobs:
  render:
    runs-on: ubuntu-latest  
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    # checkout source code
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-pandoc@v2
    - uses: r-lib/actions/setup-tinytex@v2
    # install rmarkdown
    - name: Install rmarkdown
      run: |
        Rscript -e 'install.packages("rmarkdown")'
    # copy files
    - name: Render Markdown
      run: |
        Rscript -e 'rmarkdown::render("./paper/paper.Rmd")'
    # upload new documentation
    - name: publish to github
      run: |
        git config --local core.autocrlf false
        git config --local user.email "${{ github.actor }}@users.noreply.github.com"
        git config --local user.name "${{ github.actor }}"
        git add . && git add --renormalize .
        git pull origin ${{ github.head_ref }} --autostash --rebase -X ours
        git commit --allow-empty -am "AUTO-GH ACTION: ${{ github.workflow }}"
        NO_PAGER=1 git --no-pager diff HEAD^
        git push origin
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: joss
        github_token: ${{ secrets.GITHUB_TOKEN }}