name: render_markdown

on:
  push:
    branches:
      - test_dev_tkg

jobs:
  bookdown:
    runs-on: ubuntu-latest  
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
    # checkout source code
    - uses: actions/checkout@v3
    # install rmarkdown
    - name: Install rmarkdown
      run: |
        Rscript -e 'install.packages(c("rmarkdown"))'
    # copy files
    - name: Render README
        run: |
          Rscript -e 'rmarkdown::render("./docs/my-document.Rmd", output_format = "md_document")'
    # upload new documentation
    - name: publish to github
      if: github.event_name != 'pull_request'
      run: |
        git config --global user.name "user mane"
        git config --global user.email "user email"
        export VERSION=${GITHUB_REF##*/}
        git add --all *
        git commit -m "Build markdown" || true
        git push -q origin test_dev_tkg