on:
  push:
    paths:
      - analysis/qc/20221027/example_testing.Rmd

name: Render FrEDI Output test example

jobs:
  render:
    name: Render my document
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-tinytex@v1
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown", "tidyverse", "DT", "testthat"))'
      - name: Render my document to all types
        run: Rscript -e 'rmarkdown::render("analysis/qc/20221027/example_testing.Rmd", output_format = "html_document")'
      - name: Commit results
        run: |
          git add analysis/qc/20221027/example_testing*
          git commit -m 'Test fredi' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
