name: Update System Data

on: 
  workflow_dispatch:
    inputs:
      sv_impact_type:
        type: choice
        description: Which branch SV impact type data object to update
        options:
          - impactsList_airQuality
          - impactsList_coastalProp
          - impactsList_extremeTemp
          - impactsList_htf
          - impactsList_labor
          - impactsList_roads
  
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Commit results
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git branch --set-upstream-to origin/${{ github.event.inputs.sv_impact_type }}
          git pull --depth=1 --ff https://github.com/USEPA/FrEDI_Data.git ${{ github.event.inputs.sv_impact_type }} --allow-unrelated-histories
          mv data_new/sv/${{ github.event.inputs.sv_impact_type }}* FrEDI/R/
          git branch --show-current
          git add FrEDI/R/${{ github.event.inputs.sv_impact_type }}*
          git pull origin ${{ github.head_ref }} --autostash --rebase -X ours
          git status
          git commit -am "add new ${{ github.event.inputs.sv_impact_type }} data from FrEDI_Data"
          git push