name: Update System Data

on: [push]
  
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Commit results
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git branch --set-upstream-to origin/fredi_data_cp_data_tkg
          git pull --depth=1 --ff https://github.com/USEPA/FrEDI_Data.git data_only_branch_tkg --allow-unrelated-histories
          mv data_new createSystemData/new_data
          git branch --show-current
          git add createSystemData/new_data
          git status
          git commit -m "add data"
          git remote -v
          git push --force