name: Update System Data

on: [push]
  
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Commit results
        run: |
          git pull --depth=1 --ff https://github.com/USEPA/FrEDI_Data.git data_only_branch_tkg --allow-unrelated-histories
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add --all
          git commit -am "add data"
          git push 